version: "3.9"

services:
  api:
    build: .
    container_name: beyond-media-api

    restart: unless-stopped

    ports:
      - "${PORT}:3000"

    env_file:
      - .env

    depends_on:
      - mysql

  mysql:
    image: mysql:8.4

    container_name: beyond-media-mysql

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: