import { Router } from "express";
import authRoutes from "./auth.routes";
import healthRoutes from "./health.routes";
import newsRoutes from "../module/news/news.routes";
import categoryRoutes from "../module/category/category.routes";
import subCategoryRoutes from "../module/sub-category/subcategory.routes";
import roleRoutes from "../module/roles/role.routes";
import permissionRoutes from "../module/permissions/permission.routes";
import userroleRoutes from "../module/users-roles/userrole.routes";
import userRoutes from "../module/users/user.routes";
import advertisementRoutes from "../module/advertisement/advertisement.routes";
import homeRoutes from "../module/home/home.routes";
const router = Router();

router.use("/", healthRoutes);
router.use("/api/auth", authRoutes);
router.use("/api/news", newsRoutes);
router.use("/api/categories", categoryRoutes);
router.use("/api/sub-categories", subCategoryRoutes);
router.use("/api/roles", roleRoutes);
router.use("/api/permissions", permissionRoutes);
router.use("/api/users", userroleRoutes);
router.use("/api/users", userRoutes);
router.use("/api/advertisements", advertisementRoutes);
router.use("/api/home", homeRoutes);
export default router;